---
title: "STA_138"
author: "Charles Chien"
date: "12/14/2020"
output: pdf_document
---

# Import & Modifying Dataset
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#libraries and setseed
library(readr)
library(ISLR)
library(ggplot2)
set.seed(123)

#import dataset
Byssinosis <- read_csv("Byssinosis.csv")

#turn numerical variable into factor
Byssinosis$Workspace <- as.factor(Byssinosis$Workspace)

#make long data from wide data
yes <- Byssinosis$Byssinosis
no <- Byssinosis$`Non-Byssinosis`
yesInd <- c(
  rep(0,sum(no)),
  rep(1,sum(yes))
  )
longdata <- rbind(
  Byssinosis[rep(1:72,no),1:5],
  Byssinosis[rep(1:72,yes),1:5]
)
longdata$y <- yesInd

#create train and test datasets using 50-50 split on long data
trainIndex <- sample(5419, 2710)
train = longdata[trainIndex,] 
test = longdata[-trainIndex,]

##create "yes","no" response for EDA, change name of column y
longdataeda <- longdata
longdataeda$y <- ifelse(longdata$y==1,"Yes","No")
names(longdataeda)[names(longdataeda) == "y"] <- "Byssinosis"
```

# Exploratory Data Analysis

## Employment
```{r}
ggplot(longdataeda, aes(x= Employment, fill = Byssinosis)) + geom_bar(position = position_dodge())+
  labs(y= "Number of Workers", x="Employment Years", title = "Distribution of Byssinosis by Employment Years")
```



# Variable Selection


## USing Forward BIC
```{r}
forward_BIC <- step(glm(response_train~1, binomial, train),
     scope = ~Employment*Smoking*Sex*Race*Workspace,
     direction = "forward",
     k = log(dim(train)[1]))
forward_BIC
```

Final Model: formula = response_train ~ Workspace + Smoking + Employment

## Using Both BIC
```{r}
both_BIC <- step(glm(response_train~1, binomial, train),
     scope = ~Employment*Smoking*Sex*Race*Workspace,
     direction = "both",
     k = log(dim(train)[1]))
both_BIC
```

Final Model: response_train ~ Workspace + Smoking + Employment


```{r}
Byssinosis1 <- aggregate(response_test ~ Workspace + Smoking + Employment,FUN = sum, data = test)

fitGrouped <- glm(cbind(V1,V2) ~ Workspace + Smoking + Employment, binomial, Byssinosis1)
summary(fitGrouped)

1-pchisq(0.63761, 4)
```

```{r}
Byssinosis2 <- aggregate(response_test ~ Workspace + Smoking + Employment +Workspace:Smoking + Workspace:Employment + Smoking:Employment,FUN = sum, data = test)

fitGrouped2 <- glm(cbind(V1,V2)~Workspace + Smoking + Employment +Workspace:Smoking + Workspace:Employment + Smoking:Employment, binomial, Byssinosis2)
summary(fitGrouped2)

1-pchisq(5.1934e-10, 0)
```












